export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL';
